dist: xenial
os: linux
language: node_js
node_js:
  - 12

script:
  - npm run build
  - echo "We are missing some tests!"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  target_branch: main
  on:
    branch: doc
